### ISSUE TITLE
Highlight of invalid polygon may cause crash

### ISSUE THREAD

**Issue by wonder-sk** [lutraconsulting/input#1821]
In some cases, our highlight of polygons (using Qt Quick Shapes) that have self-intersections may end up with a crash. It has been confirmed this can affect recording of new polygon features and in theory it may also cause crash when an existing polygon is picked and highlighted.

https://user-images.githubusercontent.com/193367/145278961-85bfe810-ad24-46fa-aca8-5b8e5a1a3bac.mp4

The underlying Qt problem seems to be https://bugreports.qt.io/browse/QTBUG-94233

A possible fix may be to always ensure that polygons passed to `ShapePath` are already "simple" (i.e. without self-intersecting ring) by processing them with GEOS.

Backtrace:
```
#0  QTriangulator<unsigned int>::ComplexToSimple::decompose() (this=this@entry=0x7fffffffc700) at painting/qtriangulator.cpp:939
#1  0x00007ffff3fa109a in QTriangulator<unsigned int>::triangulate() (this=this@entry=0x7fffffffc7b0) at painting/qtriangulator.cpp:785
#2  0x00007ffff3f9515d in qTriangulate(QVectorPath const&, QTransform const&, double, bool)
    (path=..., matrix=..., lod=lod@entry=1, allowUintIndices=allowUintIndices@entry=true) at painting/qtriangulator.cpp:2283
#3  0x00007fffc51a9ad4 in QQuickShapeGenericRenderer::triangulateFill(QPainterPath const&, QQuickShapeGenericRenderer::Color4ub const&, QVector<QSGGeometry::ColoredPoint2D>*, QVector<unsigned int>*, QSGGeometry::Type*, bool)                                                                                                            
    (path=..., fillColor=..., fillVertices=fillVertices@entry=0x555559a22fe8, fillIndices=fillIndices@entry=0x555559a22ff0, indexType=indexType@entry=0x555559a22ff8, supportsElementIndexUint=<optimized out>) at qquickshapegenericrenderer.cpp:436
#4  0x00007fffc51aacc4 in QQuickShapeGenericRenderer::endSync(bool) (this=0x555558107b10, async=<optimized out>) at qquickshapegenericrenderer.cpp:370
#5  0x00007fffc51a0fd4 in QQuickShapePrivate::sync() (this=this@entry=0x55555831cee0) at qquickshape.cpp:1131
#6  0x00007fffc51a11c6 in QQuickShape::updatePolish() (this=0x55555831ce20) at qquickshape.cpp:960
#7  0x00007ffff5701963 in QQuickWindowPrivate::polishItems() (this=0x5555578d2c00) at items/qquickwindow.cpp:316
#8  0x00007ffff56ad7eb in QSGThreadedRenderLoop::polishAndSync(QSGThreadedRenderLoop::Window*, bool)
    (this=this@entry=0x555557ef3f30, w=<optimized out>, inExpose=inExpose@entry=false) at scenegraph/qsgthreadedrenderloop.cpp:1522
#9  0x00007ffff56ae25a in QSGThreadedRenderLoop::handleUpdateRequest(QQuickWindow*) (this=0x555557ef3f30, window=0x555557e6f8b0)
    at scenegraph/qsgthreadedrenderloop.cpp:1376
```

**Comment by tomasMizera** [comment]
@jozef-budac or @PatrikMizera could you guys please verify that his issues is fixed now? If not, please reopen. I could not replicate it anymore after [this fix](https://github.com/lutraconsulting/input/commit/939606b4dd7dcc047b58dd3851a32a8936df57e7). It is a part of current RC

**Comment by jozef-budac** [comment]
I tried to simulate it and it looks this issue was fixed in latest master
